local lorem ={
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec semper elit ut ante consequat venenatis. Phasellus non dui commodo, luctus quam scelerisque, volutpat neque. Sed convallis ante non nulla luctus maximus. Sed sed enim nec orci mollis blandit eget aliquam dui. Nam venenatis elit tortor, ut pulvinar neque mollis sed. Morbi orci leo, dignissim sagittis justo sed, venenatis aliquam nunc. In vulputate lorem eget nunc porta, sed sollicitudin leo fringilla. Ut bibendum leo at dictum fermentum. Nulla eget malesuada felis. Maecenas fermentum libero tincidunt, euismod ante vitae, elementum tellus. Pellentesque non massa velit. Curabitur fringilla libero ut dui porta, eget pulvinar nisi euismod. Duis auctor condimentum risus, sed consequat odio congue at. Morbi auctor aliquet enim sagittis porta. Mauris a.",
"Nulla ornare orci ac eros venenatis, eu porta dolor ullamcorper. Cras vehicula tellus nec turpis ultrices molestie. Nullam tristique vestibulum mi, interdum accumsan tortor molestie ac. Nulla leo orci, fringilla nec congue in, convallis ut libero. Mauris in nibh fermentum, posuere risus vel, dapibus ipsum. Sed quis urna pharetra, dictum leo accumsan, vestibulum felis. Nunc felis nisi, condimentum quis sodales non, consectetur in quam. Vestibulum nec accumsan libero. Aenean fermentum eu dolor sed scelerisque. In hac habitasse platea dictumst. Nam.",
"Praesent sed ipsum porttitor tortor placerat facilisis. Nam consectetur, tortor vitae tristique blandit, libero erat auctor nulla, eu porttitor sapien neque sit amet turpis. Quisque malesuada ligula eros, sed finibus nibh dignissim vitae. Nulla lectus nulla, fringilla et egestas et, finibus sit amet ex. Sed sed sem eu urna sodales dapibus at faucibus nulla. Quisque rutrum imperdiet nunc, sed mattis velit semper quis. Duis et purus id lorem semper hendrerit. Donec vel orci at ante egestas blandit. Etiam pretium ornare enim vitae faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent euismod molestie ante molestie tristique. Nunc a quam nibh. Sed at efficitur libero. Curabitur dapibus ante iaculis nunc placerat, vitae maximus lectus suscipit.\
Vivamus vel felis ligula. Nulla rutrum ante vitae orci sagittis ornare. Donec ut sollicitudin est, fringilla fringilla libero. Aenean et ex rhoncus est gravida aliquet eu nec neque. Aenean ac purus sed odio dignissim facilisis in tempor justo. Sed vel interdum justo. Sed faucibus, erat quis euismod cursus, dolor sem lobortis metus, at elementum mauris est ut dui. Curabitur hendrerit tristique dolor quis laoreet. Aliquam mauris ligula, bibendum eget elementum vitae, viverra et nibh. Nunc ac nunc ut leo pulvinar.",
"Aenean maximus dolor et erat pulvinar posuere. Vestibulum malesuada fermentum tellus, quis pharetra est dapibus a. Proin tempus hendrerit sem quis gravida. Nam in velit facilisis, tristique turpis pretium, pretium odio. Ut tincidunt semper interdum. Maecenas consequat condimentum consectetur. Mauris suscipit risus sed sem vehicula bibendum. Sed in odio nec.",
"Mauris quis tortor augue. Curabitur dictum erat vitae elit blandit, sed imperdiet turpis ullamcorper. Morbi dictum suscipit mi, id scelerisque risus tempus non. Morbi sollicitudin lacus vitae quam blandit, ut molestie lacus bibendum. Proin ultrices gravida magna vitae molestie. Vestibulum suscipit posuere tortor, nec tincidunt enim. Integer varius, sem non scelerisque posuere, nulla mi placerat nulla, venenatis condimentum risus lacus ut nisl. Integer et libero eu enim maximus condimentum. Vivamus vitae sapien et odio pellentesque venenatis egestas vitae magna. Vestibulum imperdiet lectus urna, vitae feugiat augue tincidunt non. Curabitur semper eleifend nunc, non suscipit ex. Morbi laoreet viverra libero vel bibendum.\
\
Duis lorem massa, sagittis eu ornare ut, cursus vel quam. Donec semper eget velit ut suscipit. Nam sit amet sapien leo. Maecenas condimentum bibendum blandit. Nulla arcu dui, gravida eu tellus vitae, malesuada malesuada elit. Donec in lacus vitae tellus sodales condimentum. Ut eu enim varius, rutrum sem ac, porta justo. Duis maximus sapien et risus imperdiet ultricies.\
\
Praesent pretium luctus risus, sit amet egestas dolor varius id. Nulla facilisi. Vestibulum sit amet porttitor nisl, in accumsan eros. Vestibulum."
}

 return lorem